# Database
Dataset:
  - dataname: PascalContext
    batch_size: 16
    nworkers: 8
    lr: 0.0001
    task_dict:
      human_parts: 2
      sal: 2

  # - dataname: NYUD
  #   batch_size: 16
  #   nworkers: 8
  #   lr: 0.0001
  #   task_dict:
  #     depth: 2
  #     semseg: 2
  #     normals: 1
  #     edge: 1